import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Award, CheckCircle2, CircleDollarSign, Code2, Search, Share2, Trophy, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { faqs, services } from "@/lib/site-data";
import heroImage from "@/assets/arn-hero-office.jpg";
import aboutImage from "@/assets/arn-about-team.jpg";
import strategyImage from "@/assets/arn-strategy-team.jpg";

// No head() here: the home route inherits title/description/og/twitter from
// __root.tsx, and ships no og:image so serve-time hosting can inject the
// project's social preview (explicit og:image or latest screenshot).
export const Route = createFileRoute("/")({
  head:()=>({meta:[{title:"Digital Marketing & IT Company in Dubai | ARN"},{name:"description",content:"Grow with professional web development, SEO, paid media, software and IT services from ARN Innovation Technology Dubai."},{property:"og:title",content:"Digital Marketing & IT Company in Dubai | ARN"},{property:"og:description",content:"Complete digital marketing and technology solutions for Dubai businesses."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),
  component: Index,
});

// IMPORTANT: Replace this placeholder. See ./README.md for routing conventions.
function Index() {
  const featured=services.filter(s=>["digital-marketing","social-media-marketing","pay-per-click","web-development","search-engine-optimization","custom-software-development"].includes(s.slug));
  return <main>
    <section className="relative min-h-[650px] overflow-hidden bg-hero"><img src={heroImage} width={1920} height={900} alt="ARN technology specialists collaborating in a Dubai office" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-0 hero-overlay"/><div className="site-container relative z-10 flex min-h-[650px] items-center py-20"><div className="max-w-3xl"><h1 className="text-4xl font-semibold leading-none text-primary-foreground sm:text-5xl md:text-[52px]">Digital Marketing and IT<br/>Company in Dubai</h1><p className="mt-8 max-w-2xl font-body text-lg leading-[29px] text-primary-foreground">Improve your online presence with professional web design and development. Use effective SEO techniques and focused digital marketing services. Top companies in Dubai trust these services.</p><Button asChild variant="quote" size="quote" className="mt-8 rounded-none"><Link to="/contact">Get A Free Quote <ArrowRight/></Link></Button></div></div></section>
    <section className="relative -mt-16 z-10"><div className="site-container grid gap-5 sm:grid-cols-2 lg:grid-cols-6">{featured.map(s=>{const Icon=s.icon;return <Link to="/services/$slug" params={{slug:s.slug}} key={s.slug} className="feature-tile"><Icon className="size-14 text-primary"/><h2 className="mt-7 text-center text-xl font-medium leading-8">{s.title}</h2></Link>})}</div></section>
    <section className="site-container grid gap-12 py-24 lg:grid-cols-2"><img src={aboutImage} width={900} height={1100} loading="lazy" alt="ARN consultants reviewing a digital project" className="h-full max-h-[680px] w-full object-cover"/><div className="self-center"><span className="eyebrow">About Us</span><h2 className="section-title mt-5">Leading Digital Marketing and IT Solution Company in Dubai</h2><div className="mt-5 border-l-2 border-primary pl-6"><p className="body-copy">With over 12+ years of experience, ARN Innovation Technology combines skilled IT experts and creative marketing specialists.</p><p className="body-copy mt-3">We help your business grow. As a trusted IT company in Dubai, we provide strong digital solutions. Our services include web solutions, custom software development, SEO, and digital marketing.</p><p className="body-copy mt-3">Our experienced team has helped companies across Dubai build strong online brands and achieve measurable success.</p></div><div className="mt-7 flex flex-wrap items-center gap-5 border-t border-border pt-7"><Button asChild className="rounded-none"><a href="tel:+971048341191">Call for Help</a></Button><div><span className="text-sm text-muted-foreground">Call for help</span><strong className="block text-xl">+971 04 834 1191</strong></div></div></div></section>
    <section className="bg-muted py-16"><div className="site-container"><p className="text-center text-sm font-semibold uppercase text-primary">Our Key Clients</p><h2 className="section-title mt-2 text-center">Trusted by ambitious businesses</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{["natco","YallaBattery","Dubai SMEs"].map(x=><div key={x} className="grid h-28 place-items-center bg-background text-2xl font-semibold text-muted-foreground shadow-sm">{x}</div>)}</div></div></section>
    <section className="site-container py-20"><div className="text-center"><span className="eyebrow">Our Services</span><h2 className="section-title mt-5">What We Offer</h2></div><div className="mx-auto mt-12 grid max-w-5xl gap-6 md:grid-cols-2 lg:grid-cols-4">{services.filter(s=>["cloud-solutions","digital-marketing","social-media-marketing","advertising-ppc-solutions"].includes(s.slug)).map(s=>{const Icon=s.icon;return <Link to="/services/$slug" params={{slug:s.slug}} className="service-card text-center" key={s.slug}><div className="mx-auto grid size-16 place-items-center rounded-full bg-primary"><Icon className="text-primary-foreground"/></div><h3 className="mt-5 font-semibold">{s.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{s.short}</p></Link>})}</div><div className="mt-10 text-center"><Button asChild className="rounded-none"><Link to="/services">Explore Our Services</Link></Button></div></section>
    <section className="bg-muted py-20"><div className="site-container text-center"><span className="eyebrow">Methodology</span><h2 className="section-title mt-5">Our Proven Process</h2><div className="mx-auto mt-10 grid max-w-4xl gap-4 md:grid-cols-4">{["Ideate","Plan","Execute","Implement"].map((x,i)=><div key={x}><div className="mx-auto grid size-20 place-items-center rounded-full bg-background shadow-md"><span className="text-2xl font-semibold text-primary">0{i+1}</span></div><div className="mt-4 bg-primary px-4 py-3 font-semibold text-primary-foreground">{x}</div></div>)}</div></div></section>
    <section className="site-container py-20"><div className="text-center"><span className="eyebrow">Why choose Us?</span><h2 className="section-title mt-5">Why Businesses Choose ARN IT</h2><p className="body-copy mx-auto mt-4 max-w-2xl">We don’t just deliver services—we deliver measurable growth, clear communication, and long-term success.</p></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[["We Understand Your Goals","Every business is unique, so our team listens carefully before creating a clear digital roadmap."],["Strategies That Deliver Results","Creative marketing with technical skills, from SEO and social media to custom web development."],["We Build Long Term Success","Sustainable growth is at the heart of everything we do, with strategies designed to last."]].map(([t,d],i)=><article key={t} className={i===1?"choice-card-active":"choice-card"}>{i===1?<img src={strategyImage} width={1200} height={720} loading="lazy" alt="ARN strategy team" className="h-40 w-full object-cover"/>:<div className="grid h-40 place-items-center bg-muted"><CheckCircle2 className="size-14 text-primary"/></div>}<div className="p-6 text-center"><h3 className="text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 opacity-80">{d}</p></div></article>)}</div></section>
    <section className="bg-primary py-12 text-primary-foreground"><div className="site-container grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[{icon:Users,value:"50+",label:"Team members"},{icon:Award,value:"92%",label:"Client Retention"},{icon:CheckCircle2,value:"250+",label:"Completed projects"},{icon:Trophy,value:"12+",label:"Years of Experience"}].map(item=>{const Icon=item.icon;return <div className="flex items-center justify-center gap-4" key={item.label}><Icon className="size-9"/><div><strong className="text-3xl">{item.value}</strong><span className="block text-sm">{item.label}</span></div></div>})}</div></section>
    <section className="bg-muted py-20"><div className="site-container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><span className="eyebrow">Client Testimonials</span><h2 className="section-title mt-5">Here’s what our customers have said.</h2><p className="body-copy mt-4">Dependable technology and marketing that delivers real value.</p></div><article className="bg-background p-8 shadow-sm md:p-12"><div className="flex items-center gap-4"><CircleDollarSign className="size-11 text-success"/><div><h3 className="text-xl font-semibold">Best Web Development Company in Dubai</h3><p className="text-sm text-muted-foreground">Operations Head, Yalla Battery, Dubai</p></div></div><p className="mt-5 text-xl text-stars">★★★★★</p><p className="body-copy mt-5">Yalla Battery chose ARN Innovation Technology for our complete website development project. Their team delivered a fast, responsive website with online booking functionality and optimized it for SEO, increasing our organic traffic. Excellent web development company!</p></article></div></section>
    <section className="site-container py-20"><h2 className="section-title text-center">Frequently Asked Questions</h2><div className="mx-auto mt-10 max-w-3xl">{faqs.map(([q,a],i)=><details key={q} open={i===0} className="faq-item"><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  </main>;
}
